# Generated by Django 3.2.9 on 2021-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211201_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='exp_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(null=True),
        ),
    ]
