# Generated by Django 3.2.8 on 2021-12-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.TextField(default='user')),
                ('experience_level', models.IntegerField(default=0)),
                ('is_trainer', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(default='Basic_Full_Body')),
                ('isthisthingon', models.TextField(default='NO')),
                ('description', models.TextField(default='Causes migrate')),
                ('location', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
