# Generated by Django 3.2.9 on 2021-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20211201_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='isthisthingon',
        ),
        migrations.AddField(
            model_name='plan',
            name='experience_level',
            field=models.IntegerField(default=0),
        ),
    ]
